Develop <- 2DAngularController
Neverway/neverlab pull request #13
Opened 2022-11-26 16:21 UTC by Lizband

Closes issue #9

2022-11-26 17:42 UTC, labrys requested changes
`invertHorizontalAxis` should be `invertRotationalAxis`

2022-11-26 17:46 UTC, labrys requested changes

2022-11-26 17:46 UTC, labrys commented on src/neverlab/Assets/Angular_Controller_2D.cs
> +    private Vector3 velocity;
This should be a `Vector2` and `angularVelocity`

2022-11-26 17:46 UTC, labrys commented on src/neverlab/Assets/Angular_Controller_2D.cs
> +    [SerializeField] private bool invertHorizontalAxis;
This should be `invertRotationalAxis`

2022-11-26 17:46 UTC, labrys commented on src/neverlab/Assets/Angular_Controller_2D.cs
> +	    if (Input.GetButton("TurnLeft")) velocity.z = speed;
Maybe `RotateLeft` and `RotateRight` or `RotateClockwise` and `RotateCounterClockwise`

2022-11-26 17:51 UTC, Lizband commented on src/neverlab/Assets/Angular_Controller_2D.cs
> +    private Vector3 velocity;
Converting this to a Vector2 would prohibit access to the gameObject's Z axis (which is the one we would want a 2D object to rotate around by default)

2022-11-26 18:01 UTC, labrys commented on src/neverlab/Assets/Angular_Controller_2D.cs
> +    private Vector3 velocity;
I'm pretty sure this shouldn't even be a vector for 2D and should only be an angle.

2022-11-27 17:29 UTC, labrys submitted a review, later dismissed

2022-11-28 02:42 UTC, labrys approved these changes

2022-11-28 05:22 UTC, merged