Develop <- 2DLinearController
Neverway/neverlab pull request #5
Opened 2022-10-19 20:55 UTC by Lizband

Closes issue #4

2022-10-22 00:45 UTC, labrys commented
`.idea` files were committed and should be excluded.  See #6.

2022-10-22 01:22 UTC, labrys requested changes
Your code committed the JetBrains `.idea` folder.  I created an issue for this #6 and it got merged to develop in #7.  Please rebase your code on the develop branch and push the changes for another review.

2022-10-23 00:32 UTC, labrys requested changes
Don't hard-code keys.  Instead get the axis from the input manager to use the configured key.

2022-11-19 16:57 UTC, labrys commented on src/neverlab/Assets/Linear_Controller_2D.cs
> +    private Vector3 movement;
Use a `Vector2` instead.  While we may move to a `Vector3` to combine 2D and 3D motion into a single interface, lets keep it as simple as possible and add complexity only where necessary.

2022-11-19 17:11 UTC, labrys requested changes

2022-11-19 17:11 UTC, labrys commented on src/neverlab/Assets/Linear_Controller_2D.cs
> +		    movement.x = invertHorizontalAxis switch
By making the axis inversion a scaling factor, you can set it a single time, for example in `Start` or `FixedUpdate` and multiply by it during the transform.

```
axisDirection = new Vector2(x=(invertHorizontalAxis) ? -1 : 1, y=(invertVerticalAxis) ? -1 : 1)
transform.Translate(movement * moveSpeed * axisDirection * Time.deltaTime);
```

2022-11-19 17:18 UTC, labrys requested changes

2022-11-19 17:18 UTC, labrys commented on src/neverlab/Assets/Linear_Controller_2D.cs
> +	    if (Input.GetButton("MoveLeft")) movement.x = -1 * horizontalInversion;
The scaling should be done during `FixedUpdate`, see my previous review for an example of how to do it.

2022-11-19 17:35 UTC, Lizband commented on src/neverlab/Assets/Linear_Controller_2D.cs
> +	    if (Input.GetButton("MoveLeft")) movement.x = -1 * horizontalInversion;
Why put it there? Isn't that worse for performance since then it constantly has to calculate `-1*horisontalInversion`?

2022-11-20 00:46 UTC, labrys commented on src/neverlab/Assets/Linear_Controller_2D.cs
> +	    if (Input.GetButton("MoveLeft")) movement.x = -1 * horizontalInversion;
In `Update` it calculates it even more often.

2022-11-25 01:03 UTC, labrys approved these changes

2022-11-25 01:04 UTC, merged